// AUTO-GENERATED BY scripts/build-showcase-snippets.mjs.
// The ApexX shown in the showcase is sliced out of the authored sources, so a
// panel cannot claim code the compiler would refuse. Regenerate with
// `npm run showcase:snippets`; `npm run demo:check` fails when it is stale.
// DO NOT EDIT.

export const EMAIL_APEXX = `public static EmailPipelineResult inspectPortfolio(List<Account> accounts) {
    List<Contact> contacts = accounts.flatMap(account => account.Contacts);
    List<String> emails = contacts
        .filter(contact => contact.Email != null && contact.Email.contains('@'))
        .map(contact => contact.Email.trim().toLowerCase());
    Integer hotCount = accounts.count(account => account.Rating == 'Hot');
    Boolean anyMissingNumber = accounts.any(account => account.AccountNumber == null);
    Boolean allHaveRevenue = accounts.all(account => account.AnnualRevenue != null);
    Account firstHighValue = accounts.find(account =>
        account.AnnualRevenue != null
        && account.AnnualRevenue >= 250000
    );

    return new EmailPipelineResult(
        accounts.size(),
        contacts.size(),
        emails.size(),
        emails,
        hotCount,
        anyMissingNumber,
        allHaveRevenue,
        firstHighValue == null ? null : firstHighValue.Name
    );
}`;

export const STRATEGY_APEXX = `public static StrategyResult evaluateMode(
    List<Account> accounts,
    String mode
) {
    Decimal exposureThreshold = 250000;
    Func<Account, Boolean> rule;
    String reason;

    if (mode == 'Revenue Exposure') {
        rule = (account) => account.AnnualRevenue != null
            && account.AnnualRevenue >= exposureThreshold;
        reason = 'Revenue exposure';
    } else if (mode == 'Sales Ready') {
        rule = (account) => account.Rating == 'Hot'
            && account.AccountNumber != null;
        reason = 'Sales ready';
    } else {
        rule = (account) => account.AccountNumber == null;
        reason = 'Missing account number';
    }

    return evaluateRenewalStrategy(
        accounts,
        mode,
        rule,
        reason
    );
}

public static StrategyResult evaluateRenewalStrategy(
    List<Account> accounts,
    String mode,
    Func<Account, Boolean> shouldEscalate,
    String escalationReason
) {
    Integer matchCount = accounts.count(account => shouldEscalate(account));
    Account firstMatch = accounts.find(account => shouldEscalate(account));
    List<AccountWorkItem> items = buildRenewalWork(
        accounts,
        shouldEscalate,
        escalationReason
    );

    return new StrategyResult(
        mode,
        accounts.size(),
        matchCount,
        firstMatch == null ? null : firstMatch.Name,
        items
    );
}`;

export const TUPLE_APEXX = `// AccountSignalProvider.clsx
public static Map<Id, (Decimal, Boolean)> calculate(List<Account> accounts) {
    Map<Id, (Decimal, Boolean)> signalsByAccountId =
        new Map<Id, (Decimal, Boolean)>();

    for (Account account : accounts) {
        Decimal revenuePerEmployee =
            account.AnnualRevenue == null
            || account.NumberOfEmployees == null
            || account.NumberOfEmployees <= 0
                ? null
                : account.AnnualRevenue / account.NumberOfEmployees;
        Boolean needsReview = account.AccountNumber == null
            || revenuePerEmployee == null
            || revenuePerEmployee < 10000;

        signalsByAccountId.put(
            account.Id,
            (revenuePerEmployee, needsReview)
        );
    }

    return signalsByAccountId;
}

// AccountSignalConsumer.clsx
public static AccountService.TupleDemoResult buildResult(List<Account> accounts) {
    Map<Id, (Decimal, Boolean)> signalsByAccountId =
        AccountSignalProvider.calculate(accounts);
    List<AccountService.AccountSignal> signals =
        new List<AccountService.AccountSignal>();
    Integer reviewCount = 0;

    for (Account account : accounts) {
        (Decimal revenuePerEmployee, Boolean needsReview) =
            signalsByAccountId.get(account.Id);
        if (needsReview) {
            reviewCount++;
        }
        signals.add(new AccountService.AccountSignal(
            account.Id,
            account.Name,
            revenuePerEmployee,
            needsReview
        ));
    }

    return new AccountService.TupleDemoResult(
        accounts.size(),
        reviewCount,
        signals
    );
}`;

export const DEFAULT_APEXX = `// 1 · both defaults
Boolean exactMatch = compareRevenue(left, right);

// 2 · override the first default
Boolean within1000 = compareRevenue(left, right, 1000);

// 3 · override both defaults
Boolean withinEither = compareRevenue(left, right, 250, 0.5);

public static Boolean compareRevenue(
    Account left,
    Account right,
    Decimal absoluteTolerance = 0,
    Decimal percentageTolerance = 0
) {
    if (left.AnnualRevenue == null || right.AnnualRevenue == null) {
        return false;
    }

    Decimal difference = (left.AnnualRevenue - right.AnnualRevenue).abs();
    Decimal baseline = left.AnnualRevenue.abs();
    Decimal percentageDifference = baseline == 0
        ? (difference == 0 ? 0 : 100)
        : difference / baseline * 100;

    return difference <= absoluteTolerance
        || percentageDifference <= percentageTolerance;
}`;

export const DECORATOR_APEXX = `@AuraEnabled
@UserFriendlyError(message = 'The operation failed safely. Internal details were hidden.')
public static void triggerUserFriendlyError() {
    String missingValue = null;
    missingValue.trim();
}`;

export const DECORATOR_IMPLEMENTATION = `public with sharing class UserFriendlyError implements ApexX.Decorator {
    public Object handle(ApexX.Invocation ctx, ApexX.Next next) {
        try {
            return next.call();
        } catch (Exception ex) {
            List<Type> expectedTypes = (List<Type>) ctx.config.get('expectedTypes');
            String message = (String) ctx.config.get('message');

            if (expectedTypes == null) {
                expectedTypes = new List<Type>();
            }

            throw new LwcUtil().getUserFriendlyException(ex, expectedTypes, message);
        }
    }
}`;

export const DECORATOR_CONTRACT = `// ApexX.cls · the generated support contract
public class Invocation {
    public String className;
    public String methodName;
    public List<String> parameterNames;
    public List<Object> arguments;
    public Map<String, Object> config;

    public Invocation(String className, String methodName, List<String> parameterNames, List<Object> arguments, Map<String, Object> config) {
        this.className = className;
        this.methodName = methodName;
        this.parameterNames = parameterNames;
        this.arguments = arguments;
        this.config = config;
    }
}

public interface Next {
    Object call();
}

public interface Decorator {
    Object handle(Invocation ctx, Next next);
}`;

export const WORKFLOW_APEXX = `// PortfolioRuleProvider.clsx
public static (Func<Account, Boolean>, String, Decimal) resolve(
    String mode
) {
    Decimal exposureThreshold = 250000;
    Func<Account, Boolean> rule;
    String reason;

    if (mode == 'Revenue Exposure') {
        rule = (account) => account.AnnualRevenue != null
            && account.AnnualRevenue >= exposureThreshold;
        reason = 'Revenue exposure';
    } else if (mode == 'Sales Ready') {
        rule = (account) => account.Rating == 'Hot'
            && account.AccountNumber != null;
        reason = 'Sales ready';
    } else {
        rule = (account) => account.AccountNumber == null;
        reason = 'Missing account number';
    }

    return (rule, reason, exposureThreshold);
}

// AccountService.clsx
@AuraEnabled
@UserFriendlyError(message = 'Unable to build the portfolio briefing.')
public static PortfolioBriefing runPortfolioBriefing(String mode, Decimal minimumRevenue) {
    List<Account> accounts = demoAccountsWithContacts();
    return minimumRevenue == null
        ? buildPortfolioBriefing(accounts, mode)
        : buildPortfolioBriefing(accounts, mode, minimumRevenue);
}

public static List<AccountWorkItem> buildSelectedWork(
    List<Account> accounts,
    String reason
) {
    return accounts.map(account => new AccountWorkItem(
        account.Id,
        account.Name,
        account.OwnerId,
        'High',
        reason
    ));
}

public static PortfolioBriefing buildPortfolioBriefing(
    List<Account> accounts,
    String mode = 'Revenue Exposure',
    Decimal minimumRevenue = 100000
) {
    (
        Func<Account, Boolean> matchesStrategy,
        String escalationReason,
        Decimal exposureThreshold
    ) = PortfolioRuleProvider.resolve(mode);

    List<Account> selected = accounts
        .filter(account =>
            account.AnnualRevenue != null
            && account.AnnualRevenue >= minimumRevenue
        )
        .filter(account => matchesStrategy(account));

    List<AccountWorkItem> workItems = buildSelectedWork(
        selected,
        escalationReason
    );
    List<String> stakeholderEmails = selected
        .flatMap(account => account.Contacts)
        .filter(contact => contact.Email != null)
        .map(contact => contact.Email.trim().toLowerCase());

    return new PortfolioBriefing(
        mode,
        minimumRevenue,
        exposureThreshold,
        accounts.size(),
        selected.size(),
        workItems,
        stakeholderEmails
    );
}`;

export const SCRIPT_APEXX = `// apexx/scripts/AccountAudit.apexx
List<Account> accounts = [
    SELECT Id, Name, AccountNumber, AnnualRevenue, NumberOfEmployees
    FROM Account
    WHERE Name LIKE 'ApexX Demo%'
    ORDER BY Name
];

Decimal exposureThreshold = 250000;
List<String> highExposure = accounts
    .filter(account => account.AnnualRevenue != null)
    .filter(account => account.AnnualRevenue >= exposureThreshold)
    .map(account => account.Name);

Decimal minimumPerEmployee = 10000;
Func<Account, Boolean> isEfficient = (account) => {
    if (account.AnnualRevenue == null
        || account.NumberOfEmployees == null
        || account.NumberOfEmployees <= 0) {
        return false;
    }

    return account.AnnualRevenue / account.NumberOfEmployees >= minimumPerEmployee;
};

Map<Id, (String, Decimal)> perEmployeeByAccountId = new Map<Id, (String, Decimal)>();
Integer efficient = 0;

for (Account account : accounts) {
    Decimal perEmployee = account.AnnualRevenue == null
        || account.NumberOfEmployees == null
        || account.NumberOfEmployees <= 0
            ? null
            : account.AnnualRevenue / account.NumberOfEmployees;

    perEmployeeByAccountId.put(account.Id, (account.Name, perEmployee));

    if (isEfficient(account)) {
        efficient++;
    }
}

System.debug('Accounts audited: ' + accounts.size());
System.debug('At or above ' + exposureThreshold + ' revenue: ' + highExposure);
System.debug('Efficient at ' + minimumPerEmployee + ' per employee: ' + efficient + ' of ' + accounts.size());
System.debug('Revenue per employee carried as a tuple: ' + perEmployeeByAccountId.size());`;

export const SCRIPT_GENERATED = `// scripts/apex/AccountAudit.apex · Execute Anonymous, nothing deployed
public interface ApexXFunc_8420216b86a6 {
    Boolean invoke(Account arg0);
}

public class ApexXTuple_b1160e58ac54 {
    public String item0;
    public Decimal item1;

    public ApexXTuple_b1160e58ac54(String item0, Decimal item1) {
        this.item0 = item0;
        this.item1 = item1;
    }
}

private class ApexXLambda0 implements ApexXFunc_8420216b86a6 {
    private Decimal minimumPerEmployee;

    public ApexXLambda0(Decimal minimumPerEmployee) {
        this.minimumPerEmployee = minimumPerEmployee;
    }

    public Boolean invoke(Account account) {
        if (account.AnnualRevenue == null
            || account.NumberOfEmployees == null
            || account.NumberOfEmployees <= 0) {
            return false;
        }

        return account.AnnualRevenue / account.NumberOfEmployees >= minimumPerEmployee;
    }
}

// An ApexX script: authored ApexX, compiled to a self-contained anonymous block
// in scripts/apex, which the Salesforce Apex extension can Execute or Debug.
//
// A script needs nothing deployed. The structural types its lambdas and tuples
// rely on are declared in the generated block itself.

List<Account> accounts = [
    SELECT Id, Name, AccountNumber, AnnualRevenue, NumberOfEmployees
    FROM Account
    WHERE Name LIKE 'ApexX Demo%'
    ORDER BY Name
];

Decimal exposureThreshold = 250000;
List<Account> apexxFilter0 = new List<Account>();
for (Account account : accounts) {
    if (account.AnnualRevenue != null) {
        apexxFilter0.add(account);
    }
}
List<Account> apexxFilter1 = new List<Account>();
for (Account account : apexxFilter0) {
    if (account.AnnualRevenue >= exposureThreshold) {
        apexxFilter1.add(account);
    }
}
List<String> apexxMap0 = new List<String>();
for (Account account : apexxFilter1) {
    apexxMap0.add(account.Name);
}
List<String> highExposure = apexxMap0;

Decimal minimumPerEmployee = 10000;
ApexXFunc_8420216b86a6 isEfficient = new ApexXLambda0(minimumPerEmployee);

Map<Id, ApexXTuple_b1160e58ac54> perEmployeeByAccountId = new Map<Id, ApexXTuple_b1160e58ac54>();
Integer efficient = 0;

for (Account account : accounts) {
    Decimal perEmployee = account.AnnualRevenue == null
        || account.NumberOfEmployees == null
        || account.NumberOfEmployees <= 0
            ? null
            : account.AnnualRevenue / account.NumberOfEmployees;

    perEmployeeByAccountId.put(account.Id, new ApexXTuple_b1160e58ac54(account.Name, perEmployee));

    if (isEfficient.invoke(account)) {
        efficient++;
    }
}

System.debug('Accounts audited: ' + accounts.size());
System.debug('At or above ' + exposureThreshold + ' revenue: ' + highExposure);
System.debug('Efficient at ' + minimumPerEmployee + ' per employee: ' + efficient + ' of ' + accounts.size());
System.debug('Revenue per employee carried as a tuple: ' + perEmployeeByAccountId.size());`;
