import type {
  ApexXDiagnostic,
  ListMethodCallExpression,
  TranspileOptions,
  TranspileResult,
} from "@apexx/ast";
import { parseApex, parseApexX } from "@apexx/parser";
import {
  collectIdentifiers,
  collectListVariables,
  findAvailableName,
} from "@apexx/semantics";

export function transpileApexX(
  source: string,
  options: TranspileOptions = {},
): TranspileResult {
  const parseResult = parseApexX(source, options.sourceFileName);
  const diagnostics: ApexXDiagnostic[] = [...parseResult.diagnostics];
  const listVariables = collectListVariables(source);
  const usedNames = collectIdentifiers(source);
  const listMethodCalls = parseResult.listMethodCalls.map(call => ({ ...call }));
  let output = "";
  let cursor = 0;

  for (const call of listMethodCalls) {
    const listType = listVariables.get(call.receiver);

    if (!listType) {
      diagnostics.push({
        severity: "error",
        source: "apexx-semantics",
        message: `Cannot infer List<T> element type for '${call.receiver}'. Declare it as a List<T> variable in this file for v0.1.`,
        range: call.range,
      });
      continue;
    }

    call.elementType = listType.elementType;
    call.resultTempNames = call.steps.map(() =>
      findAvailableName("apexxFilter", usedNames),
    );
    call.resultTempName = call.resultTempNames.at(-1);

    output += source.slice(cursor, call.range.start.offset);
    output += lowerListMethodCall(call);
    cursor = call.range.end.offset;
  }

  output += source.slice(cursor);

  const generated = addHeader(output, options.sourceFileName);
  const generatedParse = parseApex(generated);
  if (!generatedParse.ok) {
    diagnostics.push(...generatedParse.diagnostics);
  }

  return {
    source,
    output: generated,
    diagnostics,
    listMethodCalls,
    filters: listMethodCalls,
  };
}

function lowerListMethodCall(call: ListMethodCallExpression): string {
  const elementType = call.elementType;
  const resultNames = call.resultTempNames;

  if (!elementType || !resultNames || resultNames.length !== call.steps.length) {
    return call.originalText;
  }

  const indent = call.indent;
  const inner = `${indent}    `;
  const nested = `${indent}        `;
  const lines: string[] = [];
  let currentReceiver = call.receiver;

  for (const [index, step] of call.steps.entries()) {
    const resultName = resultNames[index];
    const lambda = step.lambda;

    lines.push(
      `${indent}List<${elementType}> ${resultName} = new List<${elementType}>();`,
      `${indent}for (${elementType} ${lambda.parameterName} : ${currentReceiver}) {`,
      `${inner}if (${lambda.body}) {`,
      `${nested}${resultName}.add(${lambda.parameterName});`,
      `${inner}}`,
      `${indent}}`,
    );

    currentReceiver = resultName;
  }

  if (call.statementKind === "assignment") {
    lines.push(`${indent}${call.targetType} = ${currentReceiver};`);
  } else {
    lines.push(`${indent}return ${currentReceiver};`);
  }

  return lines.join("\n");
}

function addHeader(source: string, sourceFileName?: string): string {
  const sourceLine = sourceFileName
    ? `// Source: ${sourceFileName}\n`
    : "";

  return `// AUTO-GENERATED BY ApexX.\n${sourceLine}// DO NOT EDIT.\n\n${source}`;
}
