import type {
  ApexXDiagnostic,
  FilterLambdaExpression,
  TranspileOptions,
  TranspileResult,
} from "@apexx/ast";
import { parseApex, parseApexX } from "@apexx/parser";
import {
  collectIdentifiers,
  collectListVariables,
  findAvailableName,
} from "@apexx/semantics";

export function transpileApexX(
  source: string,
  options: TranspileOptions = {},
): TranspileResult {
  const parseResult = parseApexX(source, options.sourceFileName);
  const diagnostics: ApexXDiagnostic[] = [...parseResult.diagnostics];
  const listVariables = collectListVariables(source);
  const usedNames = collectIdentifiers(source);
  const filters = parseResult.filters.map(filter => ({ ...filter }));
  let output = "";
  let cursor = 0;

  for (const filter of filters) {
    const listType = listVariables.get(filter.receiver);

    if (!listType) {
      diagnostics.push({
        severity: "error",
        source: "apexx-semantics",
        message: `Cannot infer List<T> element type for '${filter.receiver}'. Declare it as a List<T> variable in this file for v0.1.`,
        range: filter.range,
      });
      continue;
    }

    filter.elementType = listType.elementType;
    filter.resultTempName = findAvailableName("apexxFilter", usedNames);

    output += source.slice(cursor, filter.range.start.offset);
    output += lowerFilter(filter);
    cursor = filter.range.end.offset;
  }

  output += source.slice(cursor);

  const generated = addHeader(output, options.sourceFileName);
  const generatedParse = parseApex(generated);
  if (!generatedParse.ok) {
    diagnostics.push(...generatedParse.diagnostics);
  }

  return {
    source,
    output: generated,
    diagnostics,
    filters,
  };
}

function lowerFilter(filter: FilterLambdaExpression): string {
  const elementType = filter.elementType;
  const resultName = filter.resultTempName;

  if (!elementType || !resultName) {
    return filter.originalText;
  }

  const indent = filter.indent;
  const inner = `${indent}    `;
  const nested = `${indent}        `;
  const lines = [
    `${indent}List<${elementType}> ${resultName} = new List<${elementType}>();`,
    `${indent}for (${elementType} ${filter.parameterName} : ${filter.receiver}) {`,
    `${inner}if (${filter.predicate}) {`,
    `${nested}${resultName}.add(${filter.parameterName});`,
    `${inner}}`,
    `${indent}}`,
  ];

  if (filter.statementKind === "assignment") {
    lines.push(`${indent}${filter.targetType} = ${resultName};`);
  } else {
    lines.push(`${indent}return ${resultName};`);
  }

  return lines.join("\n");
}

function addHeader(source: string, sourceFileName?: string): string {
  const sourceLine = sourceFileName
    ? `// Source: ${sourceFileName}\n`
    : "";

  return `// AUTO-GENERATED BY ApexX.\n${sourceLine}// DO NOT EDIT.\n\n${source}`;
}

