import type { GeneratedApexSupportClass } from "@apexx/ast";
import {
  FUNC_REGISTRY_CLASS,
  TUPLE_REGISTRY_CLASS,
} from "./sharedTypes.js";

interface RegistryMember {
  name: string;
  source: string;
}

const REGISTRY_DESCRIPTIONS: Record<string, string> = {
  [FUNC_REGISTRY_CLASS]: "Shared structural function contracts.",
  [TUPLE_REGISTRY_CLASS]: "Shared structural tuple contracts.",
};

export function renderStructuralRegistry(
  className: string,
  members: RegistryMember[],
): GeneratedApexSupportClass {
  const uniqueMembers = new Map<string, RegistryMember>();
  for (const member of members) {
    uniqueMembers.set(member.name, member);
  }

  const body = [...uniqueMembers.values()]
    .sort((left, right) => left.name.localeCompare(right.name))
    .flatMap(member => [
      `    // APXX-MEMBER-BEGIN ${member.name}`,
      member.source,
      `    // APXX-MEMBER-END ${member.name}`,
      "",
    ]);

  return {
    className,
    source: [
      "// AUTO-GENERATED BY ApexX.",
      `// ${REGISTRY_DESCRIPTIONS[className] ?? "Shared compiler support."} DO NOT EDIT.`,
      "",
      `public class ${className} {`,
      ...body,
      "}",
      "",
    ].join("\n"),
  };
}

export function mergeGeneratedSupportClasses(
  supportClasses: GeneratedApexSupportClass[],
): GeneratedApexSupportClass[] {
  const ordinary = new Map<string, GeneratedApexSupportClass>();
  const registryMembers = new Map<string, Map<string, RegistryMember>>();

  for (const supportClass of supportClasses) {
    if (!(supportClass.className in REGISTRY_DESCRIPTIONS)) {
      ordinary.set(supportClass.className, supportClass);
      continue;
    }

    const members = registryMembers.get(supportClass.className)
      ?? new Map<string, RegistryMember>();
    for (const member of extractRegistryMembers(supportClass.source)) {
      members.set(member.name, member);
    }
    registryMembers.set(supportClass.className, members);
  }

  const registries = [...registryMembers.entries()].map(([className, members]) =>
    renderStructuralRegistry(className, [...members.values()]),
  );

  return [...ordinary.values(), ...registries].sort((left, right) =>
    left.className.localeCompare(right.className),
  );
}

function extractRegistryMembers(source: string): RegistryMember[] {
  const members: RegistryMember[] = [];
  const pattern =
    /^    \/\/ APXX-MEMBER-BEGIN ([A-Za-z][A-Za-z0-9_]*)\r?\n([\s\S]*?)^    \/\/ APXX-MEMBER-END \1$/gm;

  for (const match of source.matchAll(pattern)) {
    members.push({ name: match[1], source: match[2].replace(/\r?\n$/, "") });
  }

  return members;
}
